Repository micronaut-projects/micronaut-crac, pull requests merged in 2022-09, with the labels that each got.

#18 feature: Fire RefreshEvent prior to taking a snapshot
  crac/src/main/java/io/micronaut/crac/CracConfiguration.java
  crac/src/main/java/io/micronaut/crac/CracConfigurationProperties.java
  crac/src/main/java/io/micronaut/crac/CracEventPublisher.java
  crac/src/main/java/io/micronaut/crac/package-info.java
  crac/src/main/java/io/micronaut/crac/resources/NettyEmbeddedServerResource.java
  crac/src/main/java/io/micronaut/crac/resources/RefreshEventResource.java
  crac/src/main/java/io/micronaut/crac/resources/package-info.java
  crac/src/test/groovy/io/micronaut/crac/ConfigurationSpec.groovy
  crac/src/test/groovy/io/micronaut/crac/CracRegistrationSpec.groovy
  crac/src/test/groovy/io/micronaut/crac/EventSpec.groovy
  crac/src/test/groovy/io/micronaut/crac/NettySpec.groovy
  gradle.properties
  gradle/libs.versions.toml
  src/main/docs/guide/refresh.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#21 build: remove graal build on CI
  .github/workflows/graalvm.yml
Labels: relates-to: build

#24 Enable JAPICMP now 1.0.0 is released
  crac-bom/build.gradle
  crac/build.gradle
Labels: relates-to: build

#19 Only stop netty when checkpointing
  crac/src/main/java/io/micronaut/crac/resources/NettyEmbeddedServerResource.java
  crac/src/main/java/io/micronaut/crac/resources/RefreshEventResource.java
  gradle/libs.versions.toml
Labels: type: bug

#28 [crac] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build
