Repository micronaut-projects/micronaut-crac, pull requests merged in 2023-03, with the labels that each got.

#72 Prevent issue where micronaut-data-tx was required on the classpath
  crac/src/main/java/io/micronaut/crac/resources/DataSourceResource.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/CompositeDataSourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/DataSourceResourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/HikariDataSourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/HikariDelegatingDataSourceResolver.java
  crac/src/test/groovy/io/micronaut/crac/HikariUnsuspendableSpec.groovy
  settings.gradle
  test-suite-dbcp-jooq/build.gradle.kts
  test-suite-dbcp-jooq/src/test/groovy/io/micronaut/crac/DbcpAndJooqSpec.groovy
  test-suite-dbcp-jooq/src/test/groovy/io/micronaut/crac/MemoryAppender.groovy
  test-suite-dbcp-jooq/src/test/resources/logback.xml
  test-suite-hikari-jooq/build.gradle.kts
  test-suite-hikari-jooq/src/test/groovy/io/micronaut/crac/HikariAndJooqSpec.groovy
  test-suite-hikari-jooq/src/test/groovy/io/micronaut/crac/MemoryAppender.groovy
  test-suite-hikari-jooq/src/test/resources/logback.xml
Labels: type: bug

#76 Backport the Jooq and Hikari bugfix from 1.2.x
  crac/src/main/java/io/micronaut/crac/resources/DataSourceResource.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/CompositeDataSourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/DataSourceResourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/HikariDataSourceResolver.java
  crac/src/main/java/io/micronaut/crac/resources/datasources/resolver/HikariDelegatingDataSourceResolver.java
  crac/src/test/groovy/io/micronaut/crac/HikariUnsuspendableSpec.groovy
  settings.gradle
  test-suite-dbcp-jooq/build.gradle.kts
  test-suite-dbcp-jooq/src/test/groovy/io/micronaut/crac/DbcpAndJooqSpec.groovy
  test-suite-dbcp-jooq/src/test/groovy/io/micronaut/crac/MemoryAppender.groovy
  test-suite-dbcp-jooq/src/test/resources/logback.xml
  test-suite-hikari-jooq/build.gradle.kts
  test-suite-hikari-jooq/src/test/groovy/io/micronaut/crac/HikariAndJooqSpec.groovy
  test-suite-hikari-jooq/src/test/groovy/io/micronaut/crac/MemoryAppender.groovy
  test-suite-hikari-jooq/src/test/resources/logback.xml
Labels: type: bug

#70 ci: Gradle 8 and GithubAction sync
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#78 Redis support for CRaC
  buildSrc/src/main/groovy/io.micronaut.build.internal.crac-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.crac-module.gradle
  crac/src/main/java/io/micronaut/crac/resources/redis/AbstractRedisResource.java
  crac/src/main/java/io/micronaut/crac/resources/redis/CracRedisConfiguration.java
  crac/src/main/java/io/micronaut/crac/resources/redis/CracRedisConfigurationProperties.java
  crac/src/main/java/io/micronaut/crac/resources/redis/RedisCacheResource.java
  crac/src/main/java/io/micronaut/crac/resources/redis/RedisClientResource.java
  crac/src/main/java/io/micronaut/crac/resources/redis/StatefulRedisConnectionResource.java
  crac/src/main/java/io/micronaut/crac/resources/redis/package-info.java
  settings.gradle
  src/main/docs/guide/resource.adoc
  src/main/docs/guide/resource/custom.adoc
  src/main/docs/guide/resource/datasource.adoc
  src/main/docs/guide/resource/redis.adoc
  src/main/docs/guide/toc.yml
  test-suite-redis/build.gradle.kts
  test-suite-redis/src/test/groovy/io/micronaut/crac/BaseCacheSpecification.groovy
  test-suite-redis/src/test/groovy/io/micronaut/crac/CacheSpec.groovy
  test-suite-redis/src/test/groovy/io/micronaut/crac/CracRedisConfigurationSpec.groovy
  test-suite-redis/src/test/groovy/io/micronaut/crac/ExplicitCacheSpec.groovy
  test-suite-redis/src/test/groovy/io/micronaut/crac/MemoryAppender.groovy
  test-suite-redis/src/test/groovy/io/micronaut/crac/RedisStatefulConnectionSpec.groovy
  test-suite-redis/src/test/resources/logback.xml
Labels: type: enhancement

#77 [crac] Update common files for branch master
  .gitattributes
Labels: relates-to: build
